module "vault" {
  source                           = "terraform-google-modules/vault/google"
  version                          = "6.1.1"
  project_id                       = var.project_id
  allow_public_egress              = var.allow_public_egress
  allow_ssh                        = true
  domain                           = var.domain
  project_services                 = var.project_services
  kms_crypto_key                   = var.kms_crypto_key
  kms_keyring                      = var.kms_keyring
  tls_ca_subject                   = var.tls_ca_subject
  manage_tls                       = true
  tls_cn                           = var.tls_cn
  network_subnet_cidr_range        = "10.150.0.0/20"
  load_balancing_scheme            = var.load_balancing_scheme
  storage_bucket_enable_versioning = true
  storage_bucket_force_destroy     = true
  storage_bucket_location          = "EU"
  region                           = var.region
  service_account_name             = var.service_account_name
  vault_ca_cert_filename           = "root"
  vault_ui_enabled                 = true
  vault_version                    = var.vault_version
}
